### ISSUE TITLE
privileged operation doesn't work

### ISSUE THREAD

**Issue by donbowman** [kinvolk/kube-spawn#326]
If I create a privileged pod running dind (as eg we might do if using gitlab-runner):

```
kubectl apply -f - << EOF
apiVersion: v1                                                                                                                                               
kind: Pod
metadata:
  name: dind
  labels:
    role: dind
spec:
  containers:
    - name: dind
      image: docker:dind
      securityContext:
        privileged: true
EOF
```

And then I kubectl exec into it and run:

```
# docker pull alpine
# docker run --rm -it alpine sh               
```
It ends up not working:
```                                                                                                             
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"could not create session key: operation not permitted\"": unknown.
```

In the dind container we see this log:

```
time="2018-10-27T21:07:10Z" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/7428063ad54a9fafb5bf377d36f2f2c977472b67ae0001854c6e71c533a22f27/shim.sock" debug=false pid=305 
time="2018-10-27T21:07:10Z" level=info msg="shim reaped" id=7428063ad54a9fafb5bf377d36f2f2c977472b67ae0001854c6e71c533a22f27                                 
time="2018-10-27T21:07:10.253654428Z" level=error msg="stream copy error: reading from a closed fifo"                                                        
time="2018-10-27T21:07:10.498102350Z" level=error msg="7428063ad54a9fafb5bf377d36f2f2c977472b67ae0001854c6e71c533a22f27 cleanup: failed to delete container from containerd: no such container"
time="2018-10-27T21:07:10.512689130Z" level=error msg="Handler for POST /v1.38/containers/7428063ad54a9fafb5bf377d36f2f2c977472b67ae0001854c6e71c533a22f27/start returned error: OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:402: container init caused \\\"could not create session key: operation not permitted\\\"\": unknown"
```
